FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev \
    libglib2.0-0

# Set the working directory
COPY ./api_service/requirements.txt .
RUN pip install -r requirements.txt

# Copy the app files
COPY ./api_service .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]