version: '3.8'

services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile.api_service
    ports:
      - "8000:8000"
    restart: always
    environment:
      - AUTHORIZED_TOKEN=yourPassword
  
  ui_service:
    build:
      context: .
      dockerfile: Dockerfile.ui_service
    ports:
      - "3000:3000"
    restart: always
    environment:
      - AUTHORIZED_TOKEN=yourPassword

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - api-service

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"